Release the version 2025.11.6
* GAM-55 Initialize version 2025.11.6

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update docker-publish.yml

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -6,9 +6,6 @@ name: build
 # documentation.
 
 on:
-  push:
-    # Publish semver tags as releases.
-    tags: [ 'v*.*.*' ]
   pull_request:
     branches: [ "main" ]
 
@@ -33,11 +30,29 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        
+      # --- lire la version ---
+      - name: Get application version
+        id: read_version
+        run: |
+          # Installer yq pour parser le YAML
+          sudo apt-get update && sudo apt-get install -y python3-pip
+          pip3 install yq
+          
+          if [ -f version.yaml ]; then
+            # Extraire la valeur 'app.version'
+            APP_VERSION=$(yq '.app.version' version.yaml | sed 's/"//g')
+            echo "Version lue: $APP_VERSION"
+            # Exposer la version comme une sortie d'étape
+            echo "APP_VERSION=$APP_VERSION" >> $GITHUB_OUTPUT
+          else
+            echo "::error::version.yaml non trouvé ou 'app.version' manquant."
+            exit 1
+          fi
 
       # Install the cosign tool except on PR
       # https://github.com/sigstore/cosign-installer
       - name: Install cosign
-        if: github.event_name != 'pull_request'
         uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
         with:
           cosign-release: 'v2.2.4'
@@ -51,7 +66,6 @@ jobs:
       # Login against a Docker registry except on PR
       # https://github.com/docker/login-action
       - name: Log into registry ${{ env.REGISTRY }}
-        if: github.event_name != 'pull_request'
         uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
         with:
           registry: ${{ env.REGISTRY }}
@@ -65,6 +79,10 @@ jobs:
         uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
         with:
           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+          tags: |
+            type=raw,value=${{ steps.read_version.outputs.APP_VERSION }}
+            type=raw,value=${{ github.event.pull_request.head.sha }}
+            
 
       # Build and push Docker image with Buildx (don't push on PR)
       # https://github.com/docker/build-push-action
@@ -73,7 +91,7 @@ jobs:
         uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
         with:
           context: .
-          push: ${{ github.event_name != 'pull_request' }}
+          push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha
@@ -85,7 +103,6 @@ jobs:
       # transparency data even for private images, pass --force to cosign below.
       # https://github.com/sigstore/cosign
       - name: Sign the published Docker image
-        if: ${{ github.event_name != 'pull_request' }}
         env:
           # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
           TAGS: ${{ steps.meta.outputs.tags }}
